/**
 * A list of common medication names
 */
export const drugNameList = [
    'Acetaminophen',
    'Aleve',
    'ALPRAZOLAM',
    'AMLODIPINE BESYLATE',
    'Amoxicillin',
    'Aripiprazole',
    'Aspirin',
    'ATORVASTATIN',
    'BACLOFEN',
    'Bupropion',
    'Buspirone',
    'Carvedilol',
    'CEPHALEXIN',
    'chlordiazePOXIDE',
    'CITALOPRAM',
    'CLONAZEPAM',
    'Clonidine',
    'CYCLOBENZAPRINE',
    'Divalproex',
    'DULOXETINE HCL',
    'Eliquis',
    'Escitalopram',
    'FLUOXETINE',
    'GABAPENTIN',
    'Hydroxyzine',
    'Ibuprofen',
    'lamoTRIgine',
    'levETIRAcetam',
    'LEVOTHYROXINE',
    'LISINOPRIL',
    'LORAZEPAM',
    'LOSARTAN POTASSIUM',
    'Magnesium',
    'MELATONIN',
    'Meloxicam',
    'METFORMIN',
    'Methocarbamol',
    'Metoprolol',
    'MIRTAZAPINE',
    'Naltrexone',
    'NAPROXEN',
    'Olanzapine',
    'OMEPRAZOLE',
    'ONDANSETRON',
    'PANTOPRAZOLE',
    'Prazosin',
    'Prednisone',
    'Propranolol',
    'QUETIAPINE',
    'RISPERIDONE',
    'Sertraline',
    'Spironolactone',
    'Suboxone',
    'TIZANIDINE',
    'TOPIRAMATE',
    'Tramadol',
    'Trazadone',
    'TRAZODONE',
    'Tylenol',
    'Venlafaxine',
    'Vraylar'
];

export default drugNameList;
